### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by DarkMinstrel** [DarkMinstrel/AnimatedSpriteProgressBar#1]
![example](https://cloud.githubusercontent.com/assets/12033349/12432479/241102aa-bf04-11e5-9609-7d2b00c4d867.gif)

![image](https://cloud.githubusercontent.com/assets/12033349/12432011/65dd16b8-bf01-11e5-89ed-550f2e457637.png)

**Comment by OunmanNgampeerapong** [comment]
Ok
